#!/usr/bin/env python
# Copyright 2011 Matt Larson
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#      http://www.apache.org/licenses/LICENSE-2.0
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

from __future__ import print_function
import os
import sys
from ConfigParser import SafeConfigParser
try:
    import psutil
except:
    print("Error importing psutil", file=sys.stderr)
    print("If you do not have psutil installed, please get it:",
          file=sys.stderr)
    print("    http://code.google.com/p/psutil/", file=sys.stderr)
    sys.exit(1)
from pwd import getpwuid
try:
    from CGroupMon.CGroup import CGroup
except:
    print("Error importing CGroupMon modules, are your path settings correct?")
    sys.exit(1)

if __name__ == "__main__":
    config = SafeConfigParser()
    #Load config file if it exists
    configfile = os.path.expanduser('~/.cgroupmon')
    if(os.path.exists(configfile)):
        config.read(configfile)
    #Check if cgroup directory provided in config exists
    if (config.has_option('default', 'cgroupdir')) and not \
            (os.path.isdir(config.get('default', 'cgroupdir'))):
        print("cgroupdir in config file does not exist, attempting to" + 
              " autodetect",
              file=sys.stderr)
        config.remove_option('default', 'cgroupdir')
    #Attempt to find mounted cgroup directory
    if not config.has_option('default', 'cgroupdir'):
        import re
        import subprocess
        pattern = re.compile("[\w]* on (\S*) type cgroup")
        p = subprocess.Popen("mount", stdout=subprocess.PIPE)
        config.set('default', 'cgroupdir',
                       re.search(pattern, p.stdout.read()).groups()[0])
        if not os.path.isdir(config.get('default', 'cgroupdir')):
            print("Could not find a valid cgroup directory", file=sys.stderr)
            print("Make sure your cgroup directory is mounted", file=sys.stderr)
            sys.exit(1)
    #Lets command line options override config file for interface
    if "curses" in sys.argv:
        config.set('default', 'ui', 'curses')
    elif "echo" in sys.argv:
        config.set('default', 'ui', 'echo')
    #Run the curses interface
    if((config.has_option('default', 'ui')) and (config.get('default', 'ui') 
                                                 == 'curses')):
        try:
            import curses
        except:
            print("Error importing curses", file=sys.stderr)
            print("Please make sure ncurses is installed via your package "
                  + "manager", file=sys.stderr)
            sys.exit(1)
        from CGroupMon.CursesUI import CursesUI
        CursesUI(config.get('default', 'cgroupdir'), config=config).run()
        sys.exit(0)
    else:
        if (config.has_option('default', 'ui')) and \
                (config.get('default', 'ui') != "echo"):
            print("UI in config file not recognized, use curses or echo",
                  file=sys.stderr)
        #Defaults to echo interface
        print(repr(CGroup(config.get('default', 'cgroupdir'))).strip())
        sys.exit(0)
