#!/usr/bin/env python
# Copyright 2011 Matt Larson
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#      http://www.apache.org/licenses/LICENSE-2.0
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

import os
import sys
try:
    import psutil
except:
    print("Error importing psutil")
    print("If you do not have psutil installed, please get it:")
    print("    http://code.google.com/p/psutil/")
    sys.exit(1)
from pwd import getpwuid
from CGroupMon.CGroup import CGroup

if __name__ == "__main__":
    cdir = "/sys/fs/cgroup/user"
    if not os.path.isdir(cdir):
        cdir = "/dev/cgroup/user"
    if "curses" in sys.argv:
        try:
            import curses
        except:
            print("Error importing curses")
            print("Please make sure ncurses is installed via your package manager")
            sys.exit(1)
        from CGroupMon import CursesUI
        CursesUI.run(cdir)
    elif "gtk" in sys.argv:
        print("GTK+ interface isn't working yet")
    else:
        print(repr(CGroup(cdir)).strip())
    
